### ISSUE TITLE
v3.0.3 throws "Cannot read property 'replace' of undefined"

### ISSUE THREAD

**Issue by EvNaverniouk** [jscs-dev/node-jscs#2219]
After upgrading to 3.0.2, I can't seem to be able to get JSCS to work. Running the `jscs` CLI returns this error:

```
TypeError: Cannot read property 'replace' of undefined
    at renderLine (/Users/test/my_project/node_modules/jscs/lib/errors.js:266:16)
    at Object.Errors.explainError (/Users/test/my_project/node_modules/jscs/lib/errors.js:197:13)
    at /Users/test/my_project/node_modules/jscs/lib/reporters/console.js:16:36
    at Array.forEach (native)
    at /Users/test/my_project/node_modules/jscs/lib/reporters/console.js:14:35
    at Array.forEach (native)
    at Object.module.exports [as writer] (/Users/test/my_project/node_modules/jscs/lib/reporters/console.js:9:22)
    at /Users/test/my_project/node_modules/jscs/lib/cli.js:149:18
    at Array.<anonymous> (/Users/test/my_project/node_modules/vow/lib/vow.js:712:56)
    at Immediate.callFns [as _onImmediate] (/Users/test/my_project/node_modules/vow/lib/vow.js:23:35)
```

My .jscsrc is:

```
{
	"excludeFiles": [
		"html/build/**",
		"html/js/examples/**",
		"html/test/jasmine-2.4.1/**"
	],

	"disallowKeywords": ["with"],
	"disallowMultipleLineStrings": true,
	"disallowNamedUnassignedFunctions": true,
	"disallowNewlineBeforeBlockStatements": true,
	"disallowOperatorBeforeLineBreak": ["."],
	"disallowQuotedKeysInObjects": "allButReserved",
	"disallowSpaceAfterPrefixUnaryOperators": ["++", "--", "+", "~"],
	"disallowSpaceBeforeBinaryOperators": ["!"],
	"disallowSpacesInsideArrayBrackets": "all",
	"disallowSpacesInsideBrackets": true,
	"disallowSpacesInsideObjectBrackets": "all",
	"disallowTrailingComma": true,
	"disallowTrailingWhitespace": true,
	"requireAnonymousFunctions": true,
	"requireCapitalizedConstructors": true,
	"requireCommaBeforeLineBreak": true,
	"requireCurlyBraces": ["for", "try", "catch"],
	"requireLineBreakAfterVariableAssignment": true,
	"requireOperatorBeforeLineBreak": ["?", "=", "+", "-", "/", "*", "==", "===", "!=", "!==", ">", ">=", "<", "<="],
	"requirePaddingNewLinesAfterUseStrict": true,
	"requirePaddingNewLinesBeforeExport": true,
	"requireParenthesesAroundIIFE": true,
	"requireSpaceAfterKeywords": ["do", "for", "else", "switch", "case", "void", "while", "with", "typeof", "function"],
	"requireSpaceBeforeKeywords": ["else", "while"],
	"requireSpaceBeforeObjectValues": true,
	"requireSpacesInConditionalExpression": {
		"afterTest": true,
		"beforeConsequent": true,
		"afterConsequent": true,
		"beforeAlternate": true
	},
	"requireSpacesInForStatement": true,
	"requireSpacesInFunctionDeclaration": {
		"beforeOpeningRoundBrace": true,
		"beforeOpeningCurlyBrace": true
	},
	"requireSpacesInNamedFunctionExpression": {
		"beforeOpeningCurlyBrace": true
	},
	"safeContextKeyword": ["self", "_this"],
	"validateAlignedFunctionParameters": {
		"lineBreakAfterOpeningBraces": true,
		"lineBreakBeforeClosingBraces": true
	},
	"validateIndentation": "\t",
	"validateParameterSeparator": ", "
}
```

**Comment by hzoo** [comment]
I thought we fixed this one @mdevils?

**Comment by koistya** [comment]
I have the same issue in [react-starter-kit](https://github.com/kriasoft/react-starter-kit) after upgrading to `3.0.2`

**Comment by koistya** [comment]
`3.0.3` doesn't fix it, take a look https://travis-ci.org/kriasoft/react-starter-kit/builds/123586977

**Comment by mdevils** [comment]
@hzoo I though so

Will take a look soon

**Comment by louh** [comment]
This has been happening for me for any version `3.0.x`

I went through my codebase and ran `jscs` on each file until I discovered which file was causing the error to occur, and then through each function inside that file until I narrowed down the root cause. It seems that this object destructuring assignment inside of a function parameter causes the error: https://github.com/tangrams/tangram-play/blob/master/src/js/map/map.js#L80

This is [valid ES6](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Setting_a_function_parameter's_default_value) and has been [addressed before](https://github.com/jscs-dev/node-jscs/issues/1130).

I created a very minimal test case so you can duplicate the error: https://gist.github.com/louh/0b2e74228c141afc4a34b70d3e944254

**Comment by MadRabbit** [comment]
still happening in 3.0.3

**Comment by Yixi** [comment]
I have same problem use with react

**Comment by Grygir** [comment]
Same error for static property definition (in  jscs 3.0.3)
```javascript
class Bar {
    static test = {
        foo: 'bar'
    };
}
```
That seems to be [valid code](https://babeljs.io/repl/#?evaluate=true&presets=es2015%2Cstage-0&experimental=false&loose=false&spec=false&code=class%20Bar%20%7B%0A%20%20%20%20static%20test%20%3D%20%7B%0A%20%20%20%20%20%20%20%20foo%3A%20'bar'%0A%20%20%20%20%7D%3B%0A%7D])

```
TypeError: Cannot read property 'replace' of undefined
    at renderLine (/var/www/test/node_modules/jscs/lib/errors.js:266:16)
    at Object.Errors.explainError (/var/www/test/node_modules/jscs/lib/errors.js:197:13)
    at /var/www/test/node_modules/jscs/lib/reporters/console.js:16:36
    at Array.forEach (native)
    at /var/www/test/node_modules/jscs/lib/reporters/console.js:14:35
    at Array.forEach (native)
    at Object.module.exports [as writer] (/var/www/test/node_modules/jscs/lib/reporters/console.js:9:22)
    at /var/www/test/node_modules/jscs/lib/cli.js:149:18
    at Array.<anonymous> (/var/www/test/node_modules/vow/lib/vow.js:712:56)
    at Immediate.callFns [as _onImmediate] (/var/www/test/node_modules/vow/lib/vow.js:23:35)
```

**Comment by r-murphy** [comment]
I got the same error when using esnext bind expression, which doesn't seem to be supported in cst used by jscs 3.0. Whenever there is a parse error (error.rule === "parseError"), the error has no line number.

The fixed I applied temporarily to my jscs install was this, which a least prints the underlying reason for the parse error. I'm not sure if that's the best place for the fix or if it should be as soon as the parse error is detected.

```js
explainError: function(error, colorize) {
  if (typeof error.line === 'undefined') {
    //probably a parseError, so include the rule name
    return formatErrorMessage(error.rule + ': ' + error.message, this.getFilename(), colorize);
  }
  //... the rest 
}
```

**Comment by markelog** [comment]
There is lot of different errors here and they about different things, like 
```js
export function myFunction ({ foo = false, bar = null } = {}) {
    console.log(foo, bar);
}
```
Is https://github.com/cst/cst/issues/118

static properties is about - https://github.com/cst/cst/issues/112 

And so on.

After https://github.com/cst/cst/pull/116 and with https://github.com/jscs-dev/node-jscs/commit/729db94f86902496f3962a4a97bdd91a75ab5514, errors will be outputted in a friendly manner

**Comment by UnsungHero97** [comment]
pulling in the latest changes from master fixed this issue for me:

```
"devDependencies": {
  ...
  "jscs": "git:github.com/jscs-dev/node-jscs.git",
  ...
}
```

**Comment by zxqfox** [comment]
This is enough:
```
"devDependencies": {
  ...
  "jscs": "jscs-dev/node-jscs",
  ...
}
```

**Comment by UnsungHero97** [comment]
@zxqfox cool, thanks!

**Comment by szebrowski** [comment]
For me problem still occurs. Even on the jscs-dev/node-jscs version. It's hard for me to paste example code because project is too large.

**Comment by lf94** [comment]
Reporting in the same. Version 3.0.3. May move to ESLint as suggested though on the blog. For now I'm using the fix people have suggested.

**Comment by zxqfox** [comment]
We gonna publish 3.0.4 in a few days with a fix (we hope). Can you please try master branch?

**Comment by szebrowski** [comment]
I will try it on Monday (just finished work;)

**Comment by szebrowski** [comment]
Unfortunatly, I still get 'replace' of undefined error. :(

**Comment by szebrowski** [comment]
Most basic example to get the error:
```
var m = require('mori');

function getTrNid(trNid, saveRes) {
  return trNid < 0
		? m.getIn(saveRes, [parseInt(trNid), 'nid'])
		: trNid;
};

module.exports = getTrNid;
```

Results in:

```
~/delme/node-jscs/bin/jscs -x --preset airbnb src/js/model/FlightListLeg/getTrNid.js 
validateIndentation: Invalid indentation character:      at src/js/model/FlightListLeg/getTrNid.js :
     3 |function getTrNid(trNid, saveRes) {
     4 |  return trNid < 0
     5 |  ? m.getIn(saveRes, [parseInt(trNid), 'nid'])
--------^
     6 |  : trNid;
     7 |};

validateIndentation: Invalid indentation character:      at src/js/model/FlightListLeg/getTrNid.js :
     4 |  return trNid < 0
     5 |  ? m.getIn(saveRes, [parseInt(trNid), 'nid'])
     6 |  : trNid;
--------^
     7 |};
     8 |

TypeError: Cannot read property 'replace' of undefined
    at renderLine (/home/dflt/delme/node-jscs/lib/errors.js:267:16)
    at Object.Errors.explainError (/home/dflt/delme/node-jscs/lib/errors.js:198:13)
    at /home/dflt/delme/node-jscs/lib/reporters/console.js:16:36
    at Array.forEach (native)
    at /home/dflt/delme/node-jscs/lib/reporters/console.js:14:35
    at Array.forEach (native)
    at Object.module.exports [as writer] (/home/dflt/delme/node-jscs/lib/reporters/console.js:9:22)
    at /home/dflt/delme/node-jscs/lib/cli.js:149:18
    at Array.<anonymous> (/home/dflt/delme/node-jscs/node_modules/vow/lib/vow.js:712:56)
    at Immediate.callFns [as _onImmediate] (/home/dflt/delme/node-jscs/node_modules/vow/lib/vow.js:23:35)
```
